version: '3'

services:
  local-postgres-compose:
    image: postgres
    container_name: local-postgres-compose
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database-duck